[global]
disable = ["MD013", "MD033", "MD024", "MD029", "MD034", "MD036", "MD059"]

include = [
    "docs/**/*.md",
    "README.md"
]

exclude = [
    ".git",
    ".github",
    "node_modules",
    "build"
]

respect_gitignore = true

# [MD003]
# style = "atx"  # Heading style (atx, atx_closed, setext)

# [MD007]
# indent = 4  # Unordered list indentation

# [MD013]
# line_length = 100  # Line length
# code_blocks = false  # Exclude code blocks from line length check
# tables = false  # Exclude tables from line length check
# headings = true  # Include headings in line length check

[MD044]
names = ["embrace.COM", "GitHub", "iOS", "Xcode", "macOS", "Node.js", "JavaScript", "OpenTelemetry", "OTel", "New Relic", "Datadog", "Honeycomb", "Embrace", "SDK", "API", "embrace.COM"]
code_blocks = true
html_elements = true
html_comments = true

[MD004]
style = "dash"
